AWSTemplateFormatVersion: '2010-09-09'
Description: Template for deploying a static website hosted on S3 using an SSL certificate and a domain managed in Route 53

Parameters:
    HostedZoneName:
        Type: String
        Description: the name of the hosted zone managed in Route 53
    DomainName:
        Type: String
        Description: The domain name to create in the Route 53 hosted zone
    CertificateArn:
        Type: String
        Description: The ARN of the certificate to be used by your website

Resources:
    HostingBucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Ref DomainName
            WebsiteConfiguration:
                IndexDocument: 'index.html'

    HostingBucketResourcePolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref HostingBucket
            PolicyDocument:
                Statement:
                    - Action:
                        - "s3:GetObject"
                      Effect: "Allow"
                      Resource:
                          Fn::Join:
                              - ""
                              - 
                                - "arn:aws:s3:::"
                                - !Ref HostingBucket
                                - "/*"
                      Principal: "*"

    CDNDistributionOriginAccessIdentity:
        Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: "static website distribution"

    CDNDistribution:
        Type: 'AWS::CloudFront::Distribution'
        Properties:
            DistributionConfig:
                DefaultRootObject: 'index.html'
                Aliases:
                    - !Ref DomainName
                Enabled: true
                HttpVersion: 'http2'
                DefaultCacheBehavior:
                    AllowedMethods:
                        - GET
                        - HEAD
                    Compress: true
                    TargetOriginId: S3Origin
                    ForwardedValues:
                        QueryString: true
                        Cookies:
                            Forward: none
                    ViewerProtocolPolicy: redirect-to-https
                PriceClass: PriceClass_All
                ViewerCertificate:
                    AcmCertificateArn: !Ref CertificateArn
                    SslSupportMethod: sni-only

                Origins:
                    - DomainName: !GetAtt HostingBucket.DomainName
                      Id: S3Origin
                      S3OriginConfig: 
                        OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CDNDistributionOriginAccessIdentity}

    WebDomainRecords:
        Type: 'AWS::Route53::RecordSetGroup'
        Properties: 
            HostedZoneName: !Join ['', [!Ref HostedZoneName, .]]
            RecordSets:
                - Name: !Ref DomainName
                  Type: A
                  AliasTarget:
                      HostedZoneId: Z2FDTNDATAQYW2
                      DNSName: !GetAtt CDNDistribution.DomainName
Outputs:
    FQDNWebsite:
        Description: The FQDN of the deployed website
        Value: !Sub https://{DomainName}
